---
- name: Install Git on CentOS7 
  yum: name=git state=present

- name: Configure Git report post installation
  command: "git config --global user.name '{{ git_user }}'"

- name: configuer git authentication
  command: "git config --global user.email '{{ email }}'"
  
- name: clone Git repo
  git:
    repo:  https://github.com/18414/git-practice.git
    dest: /home/ansible/git-practice
    #separate_git_dir: /home/ansible/git-practice.git
