---
- name: Installl JDK8
  yum:
    name: java-1.8.0
    state: present
  register: jdk_v


- name: Running script to check jdk installed version  
  script: devops-tools-setup_menu/files/file.sh
  register: jdk_v

- name: Checking JDK version
  debug: msg={{ jdk_v }}

- name: Set environment variable
  lineinfile: 
    path: /etc/profile
    line: "{{ item }}"
  with_items: 
    - export JAVA_HOME=/usr/lib/jvm/{{ jdk_v.stdout }}  
    - export PATH=${JAVA_HOME}/bin:${PATH}

- name: Update /etc/profile file 
  shell: source /etc/profile
     
