---
- name: Installl JDK8
  yum:
    name: java-1.8.0
    state: present

- name: Set environment variable
  lineinfile: 
    path: /etc/profile
    line: "{{ item }}"
  with_items: 
    - export JAVA_HOME=/opt/jdk1.8.0_152 
    - export PATH=${JAVA_HOME}/bin:${PATH}

- name: Update /etc/profile file 
  command: source /etc/profile
     
