---
- name: install maven on CentOS7 
  get_url:
    url: https://www-us.apache.org/dist/maven/maven-3/3.6.0/binaries/apache-maven-3.6.0-bin.tar.gz 
    dest: /opt
  
- name: untar file 
  unarchive: 
    src: /opt/apache-maven-3.6.0-bin.tar.gz
    dest: /opt/

- name: Set maven environment variable
  lineinfile:
    path: /root/.bashrc
    line: M2_HOME="/opt/apache-maven-3.6.0"
  
